# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f1d553819fd655456e9ce5003de0c18a10cb589d7c9bba213e97f19d5379423ac0493e555a42e06b94032ecb3b7001c0e568e457a02326d728bf0f831b196e
  legacy_hash_token: '7&jwn@93rR@#J)(mf'

test:
  secret_key_base: 8edba093ac9132f9239b0fe4eb15cc48fe1f965f991571ac9005af856480d4fc2a9f8a12e3f295b100828ca15d8601238d6dc8995e4303163ade5678aa8c85d9
  legacy_hash_token: '7&jwn@93rR@#J)(mf'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  legacy_hash_token: <%= ENV["LEGACY_HASH_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

qa:
  legacy_hash_token: <%= ENV["LEGACY_HASH_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>